fix: cod datos personales
20:43:59.047 [http-nio-8083-exec-8] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703
20:43:59.047 [http-nio-8083-exec-8] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - The column name cod_datos_personales was not found in this ResultSet.
20:43:59.047 [http-nio-8083-exec-8] ERROR e.c.p.util.InjectDataInContextAspect - Exception in epntech.cbdmq.pe.servicio.impl.InstructorServiceImpl.getAll() with cause = org.hibernate.exception.SQLGrammarException: Unable to find column position by name: cod_datos_personales - MESSAGE = Unable to find column position by name: cod_datos_personales; SQL [n/a]
20:43:59.047 [http-nio-8083-exec-8] ERROR e.c.p.util.InjectDataInContextAspect - org.springframework.dao.InvalidDataAccessResourceUsageException: Unable to find column position by name: cod_datos_personales; SQL [n/a]
20:43:59.047 [http-nio-8083-exec-8] ERROR e.c.p.util.InjectDataInContextAspect - org.hibernate.exception.SQLGrammarException: Unable to find column position by name: cod_datos_personales
20:43:59.047 [http-nio-8083-exec-8] ERROR e.c.p.util.InjectDataInContextAspect - org.postgresql.util.PSQLException: The column name cod_datos_personales was not found in this ResultSet.
20:43:59.048 [http-nio-8083-exec-8] ERROR e.c.p.util.InjectDataInContextAspect - Exception in epntech.cbdmq.pe.resource.InstructorResource.listar() with cause = org.hibernate.exception.SQLGrammarException: Unable to find column position by name: cod_datos_personales - MESSAGE = Unable to find column position by name: cod_datos_personales; SQL [n/a]
20:43:59.048 [http-nio-8083-exec-8] ERROR e.c.p.util.InjectDataInContextAspect - org.springframework.dao.InvalidDataAccessResourceUsageException: Unable to find column position by name: cod_datos_personales; SQL [n/a]
20:43:59.048 [http-nio-8083-exec-8] ERROR e.c.p.util.InjectDataInContextAspect - org.hibernate.exception.SQLGrammarException: Unable to find column position by name: cod_datos_personales
20:43:59.048 [http-nio-8083-exec-8] ERROR e.c.p.util.InjectDataInContextAspect - org.postgresql.util.PSQLException: The column name cod_datos_personales was not found in this ResultSet.
org.springframework.dao.InvalidDataAccessResourceUsageException: Unable to find column position by name: cod_datos_personales; SQL [n/a]
20:43:59.048 [http-nio-8083-exec-8] ERROR e.c.pe.excepcion.GestorExcepciones - Unable to find column position by name: cod_datos_personales; SQL [n/a]