feat: arreglo error  a partir de los alias
"org.hibernate.persister.entity.DiscriminatorType.getJdbcJavaType()" because "this.discriminatorType" is null
java.lang.NullPointerException: Cannot invoke "org.hibernate.persister.entity.DiscriminatorType.getJdbcJavaType()" because "this.discriminatorType" is null